version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
  pre_build:
    commands:
      - echo "Tagging Docker image..."
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION::7}
      - REPO_URI=public.ecr.aws/k8l5m5p3/public-repo
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $REPO_URI:latest .
      - docker tag $REPO_URI:latest $REPO_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo "Pushing Docker images to public ECR..."
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
      - docker push $REPO_URI:latest
      - docker push $REPO_URI:$IMAGE_TAG
      - printf "[{\ "name\ ":"public-app\ ",\ "imageUri\ ":\ "$REPO_URI:$IMAGE_TAG\ "}]" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
