version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
  pre_build:
    commands:
      - echo "Logging into ECR..."
      - docker login -u AWS -p \
          "$(aws ecr get-login-password --region us-east-1)" \
          863518413226.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=863518413226.dkr.ecr.us-east-1.amazonaws.com/test-ecr
      - IMAGE_TAG=latest
  build:
    commands:
      - docker build -t 863518413226.dkr.ecr.us-east-1.amazonaws.com/test-ecr:latest .
      - docker push 863518413226.dkr.ecr.us-east-1.amazonaws.com/test-ecr:latest
  post_build:
    commands:
      - printf '[{"name":"app","imageUri":"%s"}]' \
          863518413226.dkr.ecr.us-east-1.amazonaws.com/test-ecr:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
