version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
  pre_build:
    commands:
      - echo "Logging into ECR..."
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION::7}
      - REPO_URI=public.ecr.aws/k8l5m5p3/public-repo
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPO_URI

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $REPO_URI:latest .
      - docker tag $REPO_URI:latest $REPO_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing images..."
      - docker push $REPO_URI:latest
      - docker push $REPO_URI:$IMAGE_TAG

      - echo "Updating ECS service..."
      - aws ecs update-service --cluster cluster-2 --service task-2-service-hnn4kreu --force-new-deployment
      - aws ecs wait services-stable --cluster cluster-2 --services task-2-service-hnn4kreu
      - echo "Deployment triggered."

artifacts:
  files:
    - imagedefinitions.json
